image: maven:3-jdk-8

build:
  script: "mvn install -B"
  script: "java -jar /root/.m2/repository/CL_SpringMVC_APIRestFul_Core/CL_SpringMVC_APIRestFul_Core/0.1.0/CL_SpringMVC_APIRestFul_Core-0.1.0.jar"