image: maven:3-jdk-8

build:
  script: "mvn clean compile package"
  stage: build
  artifacts:
    name: "$CI_BUILD_NAME"
    untracked: true
    paths:
     - configs/*

develop:
  before_script:
    - "mvn clean compile package"
    - mkdir -p ~/.ssh
    - chmod 600 ssh_keys/ssh_key_codeandlearn.fr
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - 'ssh -i ssh_keys/ssh_key_codeandlearn.fr cldeploybackend@5.196.67.156 "screen -S api_develop -p 0 -X quit || true"'
  script:
    - 'ssh -i ssh_keys/ssh_key_codeandlearn.fr cldeploybackend@5.196.67.156 "rm -rf /home/cldeploybackend/develop"'
    - "scp -i ssh_keys/ssh_key_codeandlearn.fr -r target/ cldeploybackend@5.196.67.156:/home/cldeploybackend/develop"
    - "scp -i ssh_keys/ssh_key_codeandlearn.fr configs/develop.properties cldeploybackend@5.196.67.156:/home/cldeploybackend/develop/config.properties"
    - 'ssh -i ssh_keys/ssh_key_codeandlearn.fr -t cldeploybackend@5.196.67.156 "screen -S api_develop -d -m java -jar ./cl_api.jar"'
  environment: develop
  stage: deploy
  only:
    - develop
  except:
    - master
    - beta

beta:
  before_script:
    - "mvn clean compile package"
    - mkdir -p ~/.ssh
    - chmod 600 ssh_keys/ssh_key_codeandlearn.fr
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - 'ssh -i ssh_keys/ssh_key_codeandlearn.fr cldeploybackend@5.196.67.156 "screen -S api_beta -p 0 -X quit || true"'
  script:
    - 'ssh -i ssh_keys/ssh_key_codeandlearn.fr cldeploybackend@5.196.67.156 "rm -rf /home/cldeploybackend/beta"'
    - "scp -i ssh_keys/ssh_key_codeandlearn.fr -r target/ cldeploybackend@5.196.67.156:/home/cldeploybackend/beta"
    - "scp -i ssh_keys/ssh_key_codeandlearn.fr configs/beta.properties cldeploybackend@5.196.67.156:/home/cldeploybackend/beta/config.properties"
    - 'ssh -i ssh_keys/ssh_key_codeandlearn.fr -t cldeploybackend@5.196.67.156 "screen -S api_beta -d -m java -jar ./cl_api.jar"'
  environment: beta
  stage: deploy
  only:
    - beta
  except:
    - develop
    - master

production:
  before_script:
    - "mvn clean compile package"
    - mkdir -p ~/.ssh
    - chmod 600 ssh_keys/ssh_key_codeandlearn.fr
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - 'ssh -i ssh_keys/ssh_key_codeandlearn.fr cldeploybackend@5.196.67.156 "screen -S api_production -p 0 -X quit || true"'
  script:
    - 'ssh -i ssh_keys/ssh_key_codeandlearn.fr cldeploybackend@5.196.67.156 "rm -rf /home/cldeploybackend/production"'
    - "scp -i ssh_keys/ssh_key_codeandlearn.fr -r target/ cldeploybackend@5.196.67.156:/home/cldeploybackend/production"
    - "scp -i ssh_keys/ssh_key_codeandlearn.fr configs/production.properties cldeploybackend@5.196.67.156:/home/cldeploybackend/production/config.properties"
    - 'ssh -i ssh_keys/ssh_key_codeandlearn.fr -t cldeploybackend@5.196.67.156 "screen -S api_production -d -m java -jar ./cl_api.jar"'
  environment: production
  stage: deploy
  only:
    - production
  except:
    - develop
    - beta